import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import { Changa_One } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import AdminFloatingButton from "./components/AdminFloatingButton";
import SessionProvider from "./components/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const changaOne = Changa_One({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-changa-one",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistSans.variable} ${geistMono.variable} ${changaOne.variable} antialiased`}
      >
        <SessionProvider>
          {/* Top Navigation */}
          <Navigation />

          {/* Main content */}
          <main>{children}</main>

          {/* Floating Admin Button */}
          <AdminFloatingButton />
        </SessionProvider>
      </body>
    </html>
  );
}